name: venompred2
channels:
  - conda-forge
  - defaults
dependencies:
  - joblib=1.2.0
  - numpy=1.23.5
  - pandas=1.5.3
  - python=3.10.8
  - rdkit=2022.09.1
  - scikit-learn=1.0.2
  - scipy=1.10.0

